services:
  application:
    image: 339712751218.dkr.ecr.ap-northeast-2.amazonaws.com/play-qr-ecr:latest
    ports:
      - "8080:8080"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.platform/nginx/conf.d/proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - application