spring:
  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect


  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

  profiles:
    active: ${spring.profiles.active}


springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
  use-fqn: true

app:
  jwt:
    secret: ${app.jwt.secret}       # intellij 상단 run -> edit config -> enviromnent variable에 추가
