spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rockoon?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: springproject
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
      #나중에 update로 변경
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

  profiles:
    include:
      - security

  redis:
    host: localhost
    port: 6379

app:
  jwt:
    secret: ${JWT_SECRET_KEY}       # intellij 상단 run -> edit config -> environment variables에 값 추가 필요
