spring:
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.table}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: redis
    port: 6379