spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      cluster:
        nodes:
          - redis-cluster.redis.svc.cluster.local:6379