apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
#images:
#- digest: sha256:953557967227b9865de0cea108829abfb2815e083fee7e0e5cf409ed2f13cbda
#  name: gcr.io/play-barcode-dev/play-barcode-dev:v1
#  newName: gcr.io/play-barcode-dev/play-barcode-dev
