apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: play-barcode-dev
spec:
  ports:
    - port: 6379
  selector:
    app: play-barcode-dev
    tier: redis
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: play-barcode-dev-redis
  labels:
    app: play-barcode-dev
spec:
  selector:
    matchLabels:
      app: play-barcode-dev
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: play-barcode-dev
        tier: redis
    spec:
      containers:
        - image: redis:7.2
          name: redis
          ports:
            - containerPort: 6379
              name: redis