apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: play-barcode@play-barcode-dev.iam.gserviceaccount.com
  name: secret-manager-sa
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm:
      projectID: play-barcode-dev
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast3
          clusterName: play-barcode-server-cluster
          clusterProjectID:  play-barcode-dev
          serviceAccountRef:
            name: secret-manager-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: created-secret
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret-key
      remoteRef:
        key: JWT_SECRET_KEY
    - secretKey: mysql-url
      remoteRef:
        key: MY_SQL
    - secretKey: database-username
      remoteRef:
        key: DATABASE_USERNAME
    - secretKey: database-password
      remoteRef:
        key: DATABASE_PASSWORD
