apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: principal://iam.googleapis.com/projects/127256803371/locations/global/workloadIdentityPools/play-barcode-dev.svc.id.goog/subject/ns/play-barcode-dev/sa/secret-manager-sa
  name: secret-manager-sa
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm:
      projectID: play-barcode-dev
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast1-a
          clusterName: play-barcode-dev-cluster
          clusterProjectID:  play-barcode-dev
          serviceAccountRef:
            name: secret-manager-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: created-secret
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret-key
      remoteRef:
        key: JWT_SECRET_KEY
    - secretKey: mysql-url
      remoteRef:
        key: MYSQL_URL
    - secretKey: database-username
      remoteRef:
        key: DATABASE_USERNAME
    - secretKey: database-password
      remoteRef:
        key: DATABASE_PASSWORD
