apiVersion: v1
kind: Service
metadata:
  name: play-barcode-dev
spec:
  selector:
    app: play-barcode-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 35.216.94.24
