apiVersion: v1
kind: Service
metadata:
  name: play-barcode-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: play-barcode-dev
  ports:
    - name: http
      port: 80 # 로드밸런서로 트래픽이 들어오면 서비스의 80번 포트로 전달하고
      targetPort: 8080 # Pod의 8080번 포트로 전달
      protocol: TCP
