apiVersion: v1
kind: Service
metadata:
  name: play-barcode-dev
spec:
  type: NodePort
  selector:
    app: play-barcode-dev
  ports:
    - name: http
      nodePort: 30007 # 노드의 30001번 포트로 들어오면
      port: 80 # 서비스의 80번 포트로 전달하고
      targetPort: 80 # Pod의 80번 포트로 전달 30001(Node) -> 80(Service) -> 80(Pod)
      protocol: TCP